-- Public registration with single-use invitation codes generated by SUPER_ADMIN.
CREATE TABLE "registration_codes" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "created_by_user_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TIMESTAMP(3),
    "used_at" TIMESTAMP(3),
    "used_by_user_id" TEXT,

    CONSTRAINT "registration_codes_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "registration_codes_code_key" ON "registration_codes"("code");
CREATE INDEX "registration_codes_used_at_expires_at_idx" ON "registration_codes"("used_at", "expires_at");

ALTER TABLE "registration_codes"
  ADD CONSTRAINT "registration_codes_created_by_user_id_fkey"
  FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "registration_codes"
  ADD CONSTRAINT "registration_codes_used_by_user_id_fkey"
  FOREIGN KEY ("used_by_user_id") REFERENCES "users"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;
